services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: iloveactors
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: